package com.alterego.ibeaconapp;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table HUE_BRIDGE_NUPNPINFO.
 */
public class HueBridgeNUPNPInfo {

    /** Not-null value. */
    private String id;
    private String name;
    private String internalipaddress;
    private String macaddress;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HueBridgeNUPNPInfo() {
    }

    public HueBridgeNUPNPInfo(String id, String name, String internalipaddress, String macaddress) {
        this.id = id;
        this.name = name;
        this.internalipaddress = internalipaddress;
        this.macaddress = macaddress;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getInternalipaddress() {
        return internalipaddress;
    }

    public void setInternalipaddress(String internalipaddress) {
        this.internalipaddress = internalipaddress;
    }

    public String getMacaddress() {
        return macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
